version: "3.8"

services:
  dev-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: magicpost
    ports:
      - "5434:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  test-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: magicpost_test
    ports:
      - "5435:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data:
  test-db-data:
